FAE_Ratio_Biodiesel = Biodiesel
    .hover = Biodiesel ratios.
FAE_Ratio_Metabolic = Metabolic
    .hover = Metabolic ratios.
FAE_Ratio_Nutritional = Nutritional
    .hover = Nutritional ratios.
FAE_Primitive = Primitive
    .hover = Primitive.
FAE_Ratio = Ratio
    .hover = Ratio expressions.
FAE_Sum = Sum
    .hover = Sum expressions.